[package]
name = "vial"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "1.0.0-alpha.7", features = ["pratt"] }
logos = "0.15.1"

[profile.dev]
opt-level = 1
codegen-backend = "cranelift"