name:                 vial
version:              0.1.0.0
visibility:           public
id:                   vial-0.1.0.0-inplace
key:                  vial-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           nafines007@gmail.com
author:               Masashi
abi:                  inplace
exposed:              True
exposed-modules:      MyLib Vial.AST
import-dirs:
    /home/nafi/projects/vial/dist-newstyle/build/x86_64-linux/ghc-9.12.2/vial-0.1.0.0/build

library-dirs:
    /home/nafi/projects/vial/dist-newstyle/build/x86_64-linux/ghc-9.12.2/vial-0.1.0.0/build

library-dirs-static:
    /home/nafi/projects/vial/dist-newstyle/build/x86_64-linux/ghc-9.12.2/vial-0.1.0.0/build

dynamic-library-dirs:
    /home/nafi/projects/vial/dist-newstyle/build/x86_64-linux/ghc-9.12.2/vial-0.1.0.0/build

data-dir:             /home/nafi/projects/vial/.
hs-libraries:         HSvial-0.1.0.0-inplace
depends:              base-4.21.0.0-b7a5
haddock-interfaces:
    /home/nafi/projects/vial/dist-newstyle/build/x86_64-linux/ghc-9.12.2/vial-0.1.0.0/doc/html/vial/vial.haddock

haddock-html:
    /home/nafi/projects/vial/dist-newstyle/build/x86_64-linux/ghc-9.12.2/vial-0.1.0.0/doc/html/vial
